version: '3'
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile-blog
    ports:
      - 8433:8433
    depends_on:
      - redis
      - mysql
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./../../redis/data:/usr/local/redis/data/
      - ./../../redis/redis.conf:/usr/local/redis/redis.conf
  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./../../mysql/data:/var/lib/mysql
      - ./../../mysql/logs:/logs
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./../../nginx/conf/cert:/etc/nginx/cert
      - ./../../nginx/html:/usr/share/nginx/html
      - ./../../nginx/conf/conf.d:/etc/nginx/conf.d
      - ./../../nginx/logs:/etc/nginx/logs
    links:
      - blog:blogweb
    
