# Server settings

# SPRING PROFILES
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dblog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: root
    # redis缓存服务配置
    session:
        store-type: redis
    # Redis数据库索引（默认为0）
    redis:
        database: 1
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        # 连接池最大连接数（使用负值表示没有限制）
        pool:
            maxActive: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            maxWait: -1
            # 连接池中的最大空闲连接
            maxIdle: 8
            # 连接池中的最小空闲连接
            minIdle: 0
        # 连接超时时间（毫秒）
        timeout: 0