# Server settings
server:
  port: 8443
# HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png
  tomcat:
    remote-ip-header: X-Forwarded-for
    protocol-header: X-Forwarded-Proto
    port-header: X-Forwarded-Port
    uri-encoding: UTF-8
    basedir: /var/tmp/website-app
# SPRING PROFILES
spring:
  profiles:
    active: normal
  application:
    name: blog-web
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      classic_compatible: true
# HTTP ENCODING
  http:
    multipart:
        max-file-size: 2MB
        max-request-size: 10MB
    encoding:
        enabled: true
        charset: UTF-8
        force: true
  messages:
    encoding: UTF-8
  jmx:
      enabled: true
      default-domain: agentservice
  resources:
      chain:
          strategy:
              content:
                  enabled: true
                  paths: /**
  # 指定默认MimeMessage的编码，默认为: UTF-8
  mail:
    default-encoding: UTF-8
    # 指定SMTP server使用的协议，默认为: smtp
    protocol: smtp
    # 指定SMTP server host.
    host: smtp.qq.com
    port: 465
    # 指定SMTP server的用户名.
    username: 847371174@qq.com
    # 指定SMTP server登陆密码:
    password: ******
    # 指定是否在启动时测试邮件服务器连接，默认为false
    test-connection: false
    properties:
      smtp:
        auth: true
    # 腾讯企业邮箱 下两个配置必须！！！
        ssl.enable: true
        socketFactory.class: javax.net.ssl.SSLSocketFactory
        socketFactory.port: 465
        starttls.enable: true
        starttls.required: true
        connectiontimeout: 50000
        timeout: 30000
        writetimeout: 50000

# MyBatis
mybatis:
  type-aliases-package: com.yzy.blog.persistence.beans
  mapper-locations: classpath:/mybatis/*.xml
# mapper
mapper:
  mappers:
    - com.yzy.blog.plugin.BaseMapper
  not-empty: false
  identity: MYSQL
# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
banner:
  charset: UTF-8

####################################自定义配置##########################################
app:
  # 是否启用kaptcha验证码
  enableKaptcha: false
  qiniu:
    # 七牛ACCESS_KEY
    accessKey: ACCESS_KEY
    # 七牛SECRET_KEY
    secretKey: SECRET_KEY
    # 七牛BUCKET_NAME
    bucketName: BUCKET_NAME

  #请自行注册又拍云，注册地址：https://console.upyun.com/register/?invite=H1sVnkbWQ
  upyun:
    bucketName: store-yzy   #云存储的服务名
    username: ******    #操作员
    password: ******    #密码
    isDebug: true
####################################自定义配置##########################################